/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class basicLibraryTest {
    @Test void libraryRollMethodReturnsCorrectLengthArray() {
        // arrange
        basicLibrary classUnderTest = new basicLibrary();
        int rolls = 4;
        int expectedArrayLength = 4;

        // act
        ArrayList<Integer> actualResult = classUnderTest.roll(rolls);

        // assert
        assertTrue(actualResult.size() == expectedArrayLength, "roll(4) should return an array with length of 4");
    }
    @Test void libraryRollMethodReturnsArrayWithPositiveIntegersNoZeros() {
        // arrange
        basicLibrary classUnderTest = new basicLibrary();
        int rolls = 4;
        int expectedArrayLength = 4;

        // act
        ArrayList<Integer> actualResult = classUnderTest.roll(rolls);
        boolean containsZeros = !actualResult.contains(0);

        // assert
        assertTrue(containsZeros, "roll(4) should return an array with no zeroes.");
    }
    @Test void libraryRollMethodReturnsArrayWithNumsOneThruSix() {
        // arrange
        basicLibrary classUnderTest = new basicLibrary();
        int rolls = 4;

        // act
        ArrayList<Integer> actualResult = classUnderTest.roll(rolls);
        int truthTracker = 0;

        for (int item: actualResult) {
            if (item > 0 && item < 7) {
                truthTracker++;
            }
        }

        // assert
        assertTrue(truthTracker == 6, "roll(4) should return digits 1 through 6");
    }

}
