/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.ArrayList;

public class basicLibrary {
    public ArrayList<Integer> roll (int numRolls) {
        
        return new ArrayList<Integer>(numRolls);
    }
}
