/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void testRestaurantToStringFunctionsAsExpected() {
        boolean expectedMatchFound = true;
        String expectedRestaurantName = "McDo's";
        int expectedPriceCategory = 3;

        Restaurant sut = new Restaurant(expectedRestaurantName, expectedPriceCategory);

        Pattern namePattern = Pattern.compile(expectedRestaurantName, Pattern.CASE_INSENSITIVE);
        Matcher nameMatcher = namePattern.matcher(sut.toString());
        boolean nameMatchFound = nameMatcher.find();

        Pattern priceCategoryPattern = Pattern.compile(String.valueOf(expectedPriceCategory), Pattern.CASE_INSENSITIVE);
        Matcher priceCategoryMatcher = priceCategoryPattern.matcher(sut.toString());
        boolean priceCategoryMatchFound = priceCategoryMatcher.find();

        assertEquals(expectedMatchFound, nameMatchFound, "Restaurant constructor should set name property.");
        assertTrue(priceCategoryMatchFound, "Restaurant constructor should set priceCategory property.");
    }

    @Test void testReviewToStringFunctionsAsExpected(){
        String expectedAuthorName = "Alpha";
        String expectedReviewText = "biglongreview";
        int expectedStarsRating = 3;

        User author = new User(expectedAuthorName);

        Review sut = new Review(author, expectedReviewText, expectedStarsRating);
        String sutToString = sut.toString();

        Pattern authorNamePattern = Pattern.compile(expectedAuthorName, Pattern.CASE_INSENSITIVE);
        Matcher authorNameMatcher = authorNamePattern.matcher(sutToString);
        boolean authorNameMatchFound = authorNameMatcher.find();

        Pattern reviewTextPattern = Pattern.compile(expectedReviewText, Pattern.CASE_INSENSITIVE);
        Matcher reviewTextMatcher = reviewTextPattern.matcher(sutToString);
        boolean reviewTextMatchFound = reviewTextMatcher.find();

        Pattern starsRatingPattern = Pattern.compile(String.valueOf(expectedStarsRating), Pattern.CASE_INSENSITIVE);
        Matcher starsRatingMatcher = starsRatingPattern.matcher(sutToString);
        boolean starsRatingMatchFound = starsRatingMatcher.find();

        assertTrue(authorNameMatchFound, "Review constructor should set author property.");
        assertTrue(reviewTextMatchFound, "Review constructor should set review body property.");
        assertTrue(starsRatingMatchFound, "Review constructor should set star rating property.");
    }

    @Test void testRestaurantClassAddsReviewsProperly() {
        int expectedReviewCount = 1;
        int expectedReviewCount2 = 2;
        String expectedNameAuthor1 = "Alpha Bravo";
        String expectedReviewText1 = "The burger was yummie.";
        int expectedReviewRating1 = 4;
        String expectedNameAuthor2 = "Charlie Delta";
        String expectedReviewText2 = "Don't buy salad at a burger joint.";
        int expectedReviewRating2 = 2;

        User author1 = new User(expectedNameAuthor1);
        User author2 = new User(expectedNameAuthor2);

        Review review1 = new Review(author1, expectedReviewText1, expectedReviewRating1);
        Review review2 = new Review(author2, expectedReviewText2, expectedReviewRating2);

        Restaurant mcDonalds = new Restaurant("McDo's", 3);

        assertEquals(0, mcDonalds.reviews.size());

        boolean actualAddedReview1 = mcDonalds.addReview(review1);

        assertTrue(actualAddedReview1);
        assertEquals(mcDonalds.reviews.size(), expectedReviewCount);
        System.out.println(mcDonalds);

        boolean actualAddedReview2 = mcDonalds.addReview(review2);

        assertTrue(actualAddedReview2);
        assertEquals(mcDonalds.reviews.size(), expectedReviewCount2);
    }

    @Test void testRestaurantStarRatingChangesWhenReviewAdded() {
        float expectedStarRating1 = 0f;
        float expectedStarRating2 = 4f;
        float expectedStarRating3 = 3f;

        String expectedNameAuthor1 = "Alpha Bravo";
        String expectedReviewText1 = "The burger was yummie.";
        int expectedReviewRating1 = 4;
        String expectedNameAuthor2 = "Charlie Delta";
        String expectedReviewText2 = "Don't buy salad at a burger joint.";
        int expectedReviewRating2 = 2;

        User author1 = new User(expectedNameAuthor1);
        User author2 = new User(expectedNameAuthor2);

        Review review1 = new Review(author1, expectedReviewText1, expectedReviewRating1);
        Review review2 = new Review(author2, expectedReviewText2, expectedReviewRating2);

        Restaurant mcDonalds = new Restaurant("McDo's", 3);
        System.out.println(mcDonalds);
        float actualStarRating = mcDonalds.stars;
        assertEquals(expectedStarRating1, actualStarRating,
                "A restaurant with no reviews has a rating of 0.");

        mcDonalds.addReview(review1);
        System.out.println(mcDonalds);
        actualStarRating = mcDonalds.stars;
        assertEquals(expectedStarRating2, actualStarRating,
                "Restaurant star ratings change when an initial Review is added.");

        mcDonalds.addReview(review2);
        System.out.println(mcDonalds);
        actualStarRating = mcDonalds.stars;
        assertEquals(expectedStarRating3, actualStarRating,
                "Restaurant star ratings change when n additional Review is added.");
    }

    @Test void testReviewClassCanBeInstantiated() {
        String expectedUsername = "Foo Bar";
        String expectedReviewBody = "This review is full of lots of words. And sentence fragments.";
        int expectedStarsRating = 5;

        Review review = new Review(new User(expectedUsername), expectedReviewBody, 5);

        System.out.println("review.toString() output => " + review);

        assertEquals(expectedUsername, review.author.name,
                "User.name should be recorded in the Review instance.");
        assertEquals(expectedReviewBody, review.body,
                "ReviewBody property should be updated in new Review instance.");
        assertEquals(expectedStarsRating, review.stars,
                "starsRating should be stored in review.stars in new Review instance.");
    }

    @Test void testUserClassCanBeInstantiated() {
        String expectedUsername = "Foo Bar";
        int expectedReviewsWritten = 0;

        User user = new User(expectedUsername);

        String actualUserName = user.name;
        int actualReviewsWritten = user.reviewsWritten;

        System.out.println("user.toString() output => " + user);

        assertEquals(expectedReviewsWritten, actualReviewsWritten,
                "Newly instantiated User object should start with 0 reviews written.");
        assertEquals(expectedUsername, actualUserName,
                "Newly instantiated User object should have name set properly.");
    }

    @Test void testShopClassCanBeInstantiated() {
        String expectedShopName = "The FooBar Company";
        int expectedPriceCategory = 4;

        Shop shop = new Shop(expectedShopName, expectedPriceCategory);

        String actualShopName = shop.name;
        int actualPriceCategory = shop.priceCategory;

        System.out.println("Shop Class toString() => " + shop);

        assertEquals(expectedShopName, actualShopName,
                "Newly instantiated Shop should have correctly assigned Name.");
        assertEquals(expectedPriceCategory, actualPriceCategory,
                "Newly instantiated Shop should have correctly assigned priceCategory.");
    }
}
